'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Categorias
    Public Property CategoriaId As Long
    Public Property NombreCategoria As String
    Public Property EstadoCategoria As Boolean
    Public Property DescripcionCategoria As String

    Public Overridable Property Estilos As ICollection(Of Estilos) = New HashSet(Of Estilos)

End Class
