'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DetalleEstilosOperaciones
    Public Property EstiloId As String
    Public Property OperacionId As Long
    Public Property NumeroOperacion As Byte
    Public Property SAH As Double

    Public Overridable Property Estilos As Estilos
    Public Overridable Property Operaciones As Operaciones

End Class
