'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Maquinas
    Public Property MaquinaId As Long
    Public Property NombreMaquina As String
    Public Property Estandar As Nullable(Of Integer)
    Public Property EstadoMaquina As Boolean

    Public Overridable Property Operaciones As ICollection(Of Operaciones) = New HashSet(Of Operaciones)

End Class
