'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OperacionesBalanceos
    Public Property OperacionBalanceoId As Long
    Public Property TiempoEstandarSegundos As Double
    Public Property TiempoEstandarMinutos As Double
    Public Property MetaDocenasOperador As Double
    Public Property CantidadOperadores As Double
    Public Property UtilizacionOperador As String
    Public Property ParejaBalanceo As String
    Public Property FKBalanceoId As Long
    Public Property FKOperacionId As Nullable(Of Long)

    Public Overridable Property BalanceosEstilos As BalanceosEstilos
    Public Overridable Property Operaciones As Operaciones

End Class
