'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuarios
    Public Property UsuarioId As Long
    Public Property Nombre As String
    Public Property Apellido As String
    Public Property FechaNacimiento As Nullable(Of Date)
    Public Property CorreoElectronico As String
    Public Property Usuario As String
    Public Property Contrasenia As String
    Public Property FKRolId As Nullable(Of Byte)
    Public Property EstadoUsuario As Boolean

    Public Overridable Property Roles As Roles

End Class
